export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER"



//kits types

export const ADD_KIT = 'ADD_KIT'
export const ALL_KITS = 'ALL_KITS'
export const ONE_KIT = 'ONE_KIT'
export const UPDATE_KIT = 'UPDATE_KIT'



//patient types

export const ADD_PATIENT = 'ADD_PATIENT'
export const TEST_PATIENT = 'TEST_PATIENT'
export const UPDATE_TEST = 'UPDATE_TEST'
export const UPDATE_SCREEN = 'UPDATE_SCREEN'
export const ALL_PATIENTS =  'ALL_PATIENTS'
export const ONE_PATIENT = 'ONE_PATIENT'
export const ONE_SCREEN = 'ONE_SCREEN'
export const ALL_TEST ="ALL_TEST"
export const MYTESTS ="MYTESTS"


///User types

export const ADD_USER  = 'ADD_USER'
export const ALL_USERS = 'ALL_USERS'

export const GENDERMALE = 'GENDERMALE' 
export const GENDERFEMALE = 'GENDERFEMALE' 
export const  GENDER_RESULT = "GENDER_RESULT" 
export const PROVINCE_RESULT_GENDER = "PROVINCE_RESULT_GENDER" 
export const PROVINCE_RESULTS = "PROVINCE_RESULTS"

export const MALEPOSITIVE = "MALEPOSITIVE"
export const MALENEGATIVE ='MALENEGATIVE'

export const BULUAYO_NEGATIVE = 'BULUAYO_NEGATIVE'
export const BULUAYO_POSITIVE = 'BULUAYO_POSITIVE'

export const  MIDLANDS_NEGATIVE = 'MIDLANDS_NEGATIVE'
export const MIDLANDS_POSITIVE = 'MIDLANDS_POSITIVE'

export const  HARARE_NEGATIVE  ='HARARE_NEGATIVE'
          export const         HARARE_POSITIVE  = ' HARARE_POSITIVE'
          export const          MANICALAND_NEGATIVE ='MANICALAND_NEGATIVE'
          export const           MANICALAND_POSITIVE  ='MANICALAND_POSITIVE '

          export const      MASHONALAND_CENTRAL_NEGATIVE ='MASHONALAND_CENTRAL_NEGATIVE'
          export const         MASHONALAND_CENTRAL_POSITIVE  = 'MASHONALAND_CENTRAL_POSITIVE'
          export const     MASHONALAND_EAST_NEGATIVE = 'MASHONALAND_EAST_NEGATIVE'
          export const         MASHONALAND_EAST_POSITIVE  = 'MASHONALAND_EAST_POSITIVE '
          export const        MASHONALAND_WEST_POSITIVE  = 'MASHONALAND_WEST_POSITIVE'
          export const       MASHONALAND_WEST_NEGATIVE  = 'MASHONALAND_WEST_NEGATIVE'
          export const       MASVINGO_NEGATIVE = 'MASVINGO_NEGATIVE'
          export const      MASVINGO_POSITIVE  = 'MASVINGO_POSITIVE'
          export const     MATABELELAND_NORTH_NEGATIVE  = 'MATABELELAND_NORTH_NEGATIVE'
          export const     MATABELELAND_NORTH_POSITIVE =  'MATABELELAND_NORTH_POSITIVE'
          export const    MATABELELAND_SOUTH_NEGATIVE ='MATABELELAND_SOUTH_NEGATIVE'
          export const    MATABELELAND_SOUTH_POSITIVE  = 'MATABELELAND_SOUTH_POSITIVE'